-- 030 — Review queue triage table.
--
-- One table: doc_review_queue.
--   Mirrors the 14-column schema of BSF!ReviewQueue (see scripts/bootstrap-review-queue.js).
--   One row per triage item emitted by the reconciler, orphan-scan, RM dynamic builder,
--   and any other pipeline component that detects an anomaly requiring human decision.
--
-- Type ENUM lists every value in TYPE_OPTIONS from bootstrap-review-queue.js — this
-- enum is the contract; adding a new type requires an ALTER TABLE migration.
--
-- Decision ENUM mirrors DECISION_OPTIONS (pending | accept | alias | create | reject).
-- Applied variants (accept-applied, alias-applied, etc.) are stored as-is in decision
-- when the reconciler has actioned the row; they are not enum-constrained because the
-- set of applied values grows with future reconciler logic.
--
-- queue_id is the opaque RQ_<ts>_<hex> identifier generated by makeQueueId() in
-- lib/review-queue.js — used as the dedup anchor across BSF and MySQL during transition.
--
-- No is_active column: RQ rows are append-only. Resolution is expressed through the
-- decision + decided_at columns, not soft-delete. This matches BSF behavior where rows
-- are never deleted, only actioned.
--
-- file_id_fk is nullable: many RQ row types (supplier-unknown, gl-drift) are not
-- tied to a specific file.
--
-- No seeding — pipeline scripts own all data population.

CREATE TABLE IF NOT EXISTS doc_review_queue (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  queue_id      VARCHAR(64)     NOT NULL,
  type          ENUM(
    'supplier-unknown',
    'ingredient-unknown',
    'gl-drift',
    'archive-candidate',
    'inactive-candidate',
    'dynamic-vs-take-drift',
    'rm-stale',
    'rm-negative',
    'rm-orphan-mi',
    'invoice-no-dn',
    'dn-no-invoice',
    'photonote-audit',
    'sales-sku-unknown',
    'doc-classify-ambiguous',
    'invoice-line-items-needed',
    'dn-invoice-duplicate',
    'dn-low-confidence-line'
  )               NOT NULL,
  value         VARCHAR(512)    NOT NULL,
  variants      TEXT            NULL,
  count_obs     INT             NOT NULL DEFAULT 1,
  last_seen_at  DATE            NULL,
  sources       VARCHAR(512)    NULL,
  context       TEXT            NULL,
  top_match     VARCHAR(512)    NULL,
  alt_matches   TEXT            NULL,
  status        ENUM('open','in_progress','resolved','rejected') NOT NULL DEFAULT 'open',
  decision      VARCHAR(32)     NOT NULL DEFAULT 'pending',
  decided_at    DATETIME        NULL,
  decided_by    VARCHAR(128)    NULL,
  suggestions   JSON            NULL,
  dedup_key     VARCHAR(255)    NULL,
  priority      INT             NOT NULL DEFAULT 0,
  invoice_ref   VARCHAR(128)    NULL,
  file_id_fk    BIGINT UNSIGNED NULL,
  created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_queue_id              (queue_id),
  KEY idx_doc_rq_type                  (type),
  KEY idx_doc_rq_status                (status),
  KEY idx_doc_rq_decision              (decision(32)),
  KEY idx_doc_rq_dedup_key             (dedup_key),
  KEY idx_doc_rq_invoice_ref           (invoice_ref),
  KEY idx_doc_rq_file_id_fk            (file_id_fk),
  KEY idx_doc_rq_priority              (priority),
  CONSTRAINT fk_doc_rq_file            FOREIGN KEY (file_id_fk) REFERENCES doc_files(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Down-migration order:
--   DROP TABLE IF EXISTS doc_review_queue;
