-- ============================================================
-- Migration 236: backfill 21 historical contract brews
-- into bd_brewing_brewday_v2
--
-- What:
--   21 rows from v1 `bd_brewing_brewday` for contract clients
--   (BLZ Company, Brasserie du Château, Chien Bleu, BadFish,
--    MeltingPote) that were not yet present in bd_brewing_brewday_v2.
--   NYL and Chien Bleu - Moût Froid are deliberately excluded
--   (deferred per operator decision).
--
-- Why:
--   Completes the v2 migration for all in-scope contract brews,
--   unblocking downstream packaging-gate and reporting queries
--   that join bd_brewing_brewday_v2 for batch attribution.
--
-- row_hash: computed via gen_mig236_contract_brewday.py using
--   the same canonical dict + _row_hash() as ingest_bd_brewing_v2.py.
--
-- Rollback:
--   DELETE FROM bd_brewing_brewday_v2
--     WHERE audit_flags LIKE '%backfill_v1_contract_mig236%';
-- ============================================================

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BLZ Company - WestCoast Pale Ale', '1', 14, '2021-02-09 00:00:00.000000', NULL, '2021-02-09', 5, NULL, NULL, 'US-05', '4', NULL, 'STI,EMB', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', 'ca830ef13c7cbf5067d500ec507950a96bbffb9daf7badad7f1ff375663fa468')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BLZ Company - WestCoast Pale Ale', '2', 14, '2021-04-29 00:00:00.000000', NULL, '2021-04-29', 8, NULL, NULL, 'US-05', '10', NULL, 'Chateau', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '01284dc2846db3acc31a461d6345f6a8ba171f81cf5f5bce59a70bacec62bf47')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BLZ Company - WestCoast Pale Ale', '3', 14, '2021-06-23 00:00:00.000000', NULL, '2021-06-23', 11, NULL, NULL, 'US-05', '14', NULL, 'MOO8', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', 'eed10be476401cff2105482012a1703b1715c264da194e311ab58fda7779f77e')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BLZ Company - WestCoast Pale Ale', '4', 14, '2021-08-17 00:00:00.000000', NULL, '2021-08-17', 1, NULL, NULL, 'US-05', '3', NULL, '4,4', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '06e02504ffd3e638562f26ba1e3d098ef7154276ae6cce67ca80e0166080a23a')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BLZ Company - WestCoast Pale Ale', '5', 14, '2021-09-08 00:00:00.000000', NULL, '2021-09-08', 9, NULL, NULL, 'US-05', '5', NULL, 'SPY 20', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '9539195a4ae9a99d59d84c17ea1b5b388b6efb2b7edef7120215fadbfcf7d414')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BLZ Company - WestCoast Pale Ale', '6', 14, '2021-11-16 00:00:00.000000', NULL, '2021-11-16', 9, NULL, NULL, 'US-05', '10', NULL, 'MOO 18', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', 'a70f2f6b689509920b78cacf45bd4cfc88d6cc8b854fa0e287fa901f3448b428')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Brasserie du Château - Faya', '1', 16, '2021-05-12 00:00:00.000000', NULL, '2021-05-12', 6, NULL, NULL, 'US-05', '11', NULL, 'STI 117', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '7956dd068faaeca989b5c3699d207a85f10b168e5516a39c3f833dc6b66d572b')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Brasserie du Château - Faya', '2', 16, '2021-07-23 00:00:00.000000', NULL, '2021-07-23', 5, NULL, NULL, 'US-05', '17', NULL, 'MOO 11', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '7cc4f53dd0af1658c778efc6c9bdd101fe0ad3844978db03bbe63285889fad6c')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BLZ Company - Lager', '1', 11, '2022-06-24 00:00:00.000000', NULL, '2022-06-24', 1, NULL, NULL, 'W34/70', '6', NULL, 'ZEP 74', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', 'a0cf8052a56e1656e70c259e9d58a5ef6672c1b84837c1225445dbec39657cb9')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('MeltingPote - Cropette', '1', 41, '2021-07-26 00:00:00.000000', NULL, '2021-07-26', 7, NULL, NULL, 'US-05', '1', NULL, 'Starter', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '0b069be64355fbcf2146d23e93994f9ed71d12ae51251995e8af9284392679cf')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Brasserie du Château - 4.4', '3', 15, '2021-04-22 00:00:00.000000', NULL, '2021-04-22', 6, NULL, NULL, 'US-05', '9', NULL, 'EMB 129', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '43994927abc1425fdb4ea2fac65d1a40e429c588e2d9f209550ce7f04432e1a9')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Brasserie du Château - 4.4', '4', 15, '2021-06-11 00:00:00.000000', NULL, '2021-06-11', 6, NULL, NULL, 'US-05', '13', NULL, 'STI 118', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '2d5110a46e6f875c4dc1c9002206121a145d1df3895ca7e2cd502b1aaba658c6')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Brasserie du Château - 4.4', '5', 15, '2021-08-06 00:00:00.000000', NULL, '2021-08-06', 3, NULL, NULL, 'US-05', '2', NULL, 'MeltingPote - Cropette', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '1e3875a68355af64bb5f2b55fadd9182d3d13b80b50e568e3814668822711f58')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Brasserie du Château - 4.4', '6', 15, '2021-11-15 00:00:00.000000', NULL, '2021-11-15', 6, NULL, NULL, 'US-05', '9', NULL, 'SPY 22', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '0909fae36ef3e821ca9d2f80d71e944598327f170b4bdf731c90b07094bd3317')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Chien Bleu - Jasper', '15', 21, '2021-05-21 00:00:00.000000', NULL, '2021-05-21', 7, NULL, NULL, 'BE-134', '1', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', 'b77f6823ed2cb7515a0457ecb5e105e5835eb5383e3bf78d5d01121992ce3143')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Chien Bleu - Jasper', '16', 21, '2021-09-13 00:00:00.000000', NULL, '2021-09-13', 5, NULL, NULL, 'BE-134', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '7cd89e9c1b5971ecf5d346e761a7090d36f088bf89e004484848a653fa9ee53d')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Chien Bleu - Bamse', '17', 20, '2021-07-06 00:00:00.000000', NULL, '2021-07-06', 8, NULL, NULL, 'W34/70', '9', NULL, 'ZEP 48', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '48c81fc78b6b63746427d278ef987a4c937ea399bea819862f408bf16674ab92')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('Chien Bleu - Pomelo', '14', 24, '2021-02-04 00:00:00.000000', NULL, '2021-02-04', 6, NULL, NULL, 'Belle Saison', '1', NULL, 'dry', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', 'd43cdfae978473f3183cbc06cfc495a6c9bf91f583f0bbb0d872cccd44919fe4')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BadFish - Witshark', '21', 9, '2021-01-08 00:00:00.000000', NULL, '2021-01-08', 7, NULL, NULL, 'WB-06', '1', NULL, 'Starter', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '8d308615a4b523622a4297959f0edaf786f6085e3b52e59de6e0af652b8722f3')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BadFish - 915', '19', 7, '2021-02-02 00:00:00.000000', NULL, '2021-02-02', 7, NULL, NULL, 'S-189', '1', NULL, 'dry', NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '8b5b49da1c50e716d4ef1721b5c068209a41dbf52a3d9a7b1facf94ce05e40ab')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);

INSERT INTO bd_brewing_brewday_v2 (beer, batch, recipe_id_fk, submitted_at, email, event_date, cct, cct_cip, cct_cip_date, yeast, yeast_gen, new_yeast, pitched_from, yt_number, yt_cip_date, start_ferm, session_id_fk, is_tombstoned, audit_flags, row_hash) VALUES ('BadFish - Cryo IPA', '9', 8, '2021-04-27 00:00:00.000000', NULL, '2021-04-27', 7, NULL, NULL, 'Verdant', '1', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'backfill_v1_contract_mig236', '8592e54487e3581b450536393dd9d273748325e2d3ed2cde2aae5909e120b69d')
ON DUPLICATE KEY UPDATE recipe_id_fk=VALUES(recipe_id_fk), event_date=VALUES(event_date), submitted_at=VALUES(submitted_at), email=VALUES(email), cct=VALUES(cct), cct_cip=VALUES(cct_cip), cct_cip_date=VALUES(cct_cip_date), yeast=VALUES(yeast), yeast_gen=VALUES(yeast_gen), new_yeast=VALUES(new_yeast), pitched_from=VALUES(pitched_from), yt_number=VALUES(yt_number), yt_cip_date=VALUES(yt_cip_date);
